#!/usr/bin/env bash
#*****************************COPYRIGHT******************************
# (C) Crown copyright 2016 Met Office. All rights reserved.
#
# Use, duplication or disclosure of this code is subject to the restrictions
# as set forth in the licence. If no licence has been raised with this copy
# of the code, the use, duplication or disclosure of it is strictly
# prohibited. Permission to do so must first be obtained in writing from the
# Met Office Information Asset Owner at the following address:
#
# Met Office, FitzRoy Road, Exeter, Devon, EX1 3PB, United Kingdom
#*****************************COPYRIGHT******************************
# NAME
#     run_model
#
# DESCRIPTION
#     Run the drivers (via link_drivers), export the environment variables
#     as required (via driver_envar), run the model (via driver_cmd) and
#     finalize the model using the drivers (via link_drivers --finalize)

# Fail if environment variables are unset, for sanitys sake
set -eu

echo $CYLC_SUITE_RUN_DIR

# Copy scripts to work directory so they can be found
cp $CYLC_SUITE_SHARE_DIR/fcm_make_drivers/build/bin/* ./

# Run our drivers, this produces two command files
#  driver_envar containing environment variables to be exported
#  driver_cmd containing a command for the system launcher
./link_drivers --run

echo '[DRIVER_TEST_SCRIPT] Drivers successfully linked'

# Export the enviromnent variables from all the drivers
source driver_envar
# Run the aprun command and provide timing information if required
start=$(date +%s)
source driver_cmd
end=$(date +%s)

time_in_aprun=$((end-start))
echo "[DRIVER_TEST_SCRIPT] $time_in_aprun seconds are spent in APRUN"

#export time_in_aprun variable so the cpmip controller can find it if required
export time_in_aprun

# Run the drivers in finalize mode (after completion of the model). This deals
# with model standard out / standard error, and also with any file details
# required prior to the start of the next model cycle (if applicable)
echo '[DRIVER_TEST_SCRIPT] Finalizing drivers'
./link_drivers --finalize
